# Generated by Django 4.1.5 on 2023-03-31 13:48

from django.db import migrations, models
import qoyish.validators


class Migration(migrations.Migration):

    dependencies = [
        ('qoyish', '0002_add_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Model',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video', validators=[qoyish.validators.file_size]),
        ),
    ]
